<a href="https://colab.research.google.com/github/edmenciab733/quantum_quipu/blob/main/curso_informacion_cuantica/ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso de Información Cuántica


## Ejercicio 1


**1.1)**

Sea $ A = A^\dagger  $  para cualquier operador ( $ A $ ) hermitiano, se puede comprobar que  $\lambda$ es un numero real de la siguiente forma.

$ A|x\rangle = \lambda|x\rangle $ y  $ A^\dagger\langle x| = \bar{\lambda}\langle x| $

Entonces se puede escribir $  \lambda|x\rangle = \bar{\lambda}|x\rangle  $ y atendiendo que  realizar el producto interno entre si mismo se representa como  $  \langle x|x\rangle = 1 $


Considerando la propiedad hermitica  de:

$$ \langle Ax, x \rangle = \langle x, Ax \rangle $$ y reemplazando al operador $A$  por sus valores propios $$ \langle \lambda x, x \rangle = \langle x, \lambda x \rangle $$


Podemos hallar $ \lambda $ aplicando  $$  \lambda\langle x|x\rangle =  \bar{\lambda}\langle x|x\rangle  $$  o lo que es igual: $$\lambda =  \bar{\lambda} $$

 Este resultado acota solo a los numeros reales, pues cualquier valor en el campo Complejo(C) para $ \lambda $ equivaldría a que el cambio de signo en la parte imaginaria (conjugado de un número complejo) haga que la ecuación no se cumpla.

--------------

Para comprobar que ambos son los vectores propios de una operador hermitico son ortogonales, consideremos los siguientes vectores $ |v\rangle $  y $ |w\rangle $ por la igualdad $ A = A\dagger  $ podemos representar ambos vectores como: $$ A|w\rangle = \mu|w\rangle $$  $$ A|v\rangle = \lambda|v\rangle $$

Considerando la propiedad hermitica  de:

$$ \langle Av, w \rangle = \langle v, Aw \rangle $$ y reemplazando al operador $A$  por sus valores propios $$ \langle \lambda v, w \rangle = \langle v, \mu w \rangle $$

Recordar que para que dos vectores sean ortogonales debe ser  $  \langle v|w\rangle = 0 $, si tenemos en cuenta la propiedad hermitiana de $A$ y aplicamos el autovector en ambos lados de la ecuación:


 $$ \lambda \langle v, w \rangle = \mu \langle v, w \rangle $$


Podemos concluir que para que esta igualdad se dé la única manera es que el producto externo entre ambos sea $  \langle v|w\rangle = 0 $. Tener en cuenta que tienen que ser vectores no nulos. Considera que $ \lambda \neq μ $






**1.2)**


- Demostrar que $$(A + B)^\dagger  = A^\dagger + B^\dagger $$
Teniendo en cuenta que la suma de matrices se realiza sumando cada elemento de $A$ con $B$. Y, si los elementos de están dados por $ A = (v_{ij}) $ y $B = (w_{ij}) $ la suma de las matrices es igual a $ A + B = v_{ij} + w_{ij} $

Esto se puede demostrar con: $ v_{ij} = (a_1 + b_1i)  $ y $ w_{ij} = (a_2 + b_2i) $

Si aplicamos la suma de $ v_{ij} + w_{ij} = (a_1 + b_1i) + ( a_2 + b_2i) $

Podemos expresar de la siguiente manera: $z_1 = (a_1 + b_1i) $ y $ z_2 = ( a_2 + b_2i) $

$$\overline{z_1} + \overline{z_2} = (a_1 - b_1i) + ( a_2 - b_2i) $$

$$ (a_1 + a_2) - (b_1 + b_2)i $$

y

$$ \overline{z_1 + z_2}  = \overline{(a_1 + b_1i) + ( a_2 + b_2i)} $$

$$ (a_1 + a_2) - (b_1 + b_2)i $$



Bajo este principio de la suma podemos concluir que sumar operadores y luego aplicar la adjunta no cambia si primero generamos la matriz adjunta.

- Demostrar que  $$(AB)^\dagger  = B^\dagger A^\dagger $$


Suponiendo que tenemos dos vectores

 $$ A = \begin{matrix}
a & b \\
c & d
\end{matrix} $$

y

 $$ B = \begin{matrix}
e & f \\
g & h
\end{matrix} $$

Si aplicamos la multiplicación:

 $$ AB = \begin{matrix}
ae + bg & ce + dg \\
af + bh & cf + dh
\end{matrix} $$

y luego la conjugada compleja, obtenemos el resultado de $ (AB)\dagger $

 $$ (AB)^\dagger = \overline {AB} = \overline {\begin{matrix}
ae + bg & ce + dg \\
af + bh & cf + dh
\end{matrix}} = \begin{matrix}
\overline{ae + bg} & \overline{ce + dg} \\
\overline{af + bh} & \overline{cf + dh}
\end{matrix} $$



Ahora comprobemos:  $ B^\dagger A^\dagger $

Primero aplicamos la transpuesta a cada matriz de forma independiente
 $$ A^T = \begin{matrix}
a & c \\
b & d
\end{matrix} $$


 $$ B^T = \begin{matrix}
e & g \\
f & h
\end{matrix} $$


Multiplicamos ambas matrices: $B^T A^T $


$$ \begin{matrix}
{ae + bg} & {ce + gd} \\
{af + bh} & {cf + dh}
\end{matrix} $$


y luego la conjugada compleja, obtenemos el resultado de $B\dagger A\dagger $

$$
\begin{matrix}
\overline{ae + bg} & \overline{ce + dg} \\
\overline{af + bh} & \overline{cf + dh}
\end{matrix} $$


- Demostrar que $ (A^\dagger)^\dagger = A$

 $$ A = \begin{matrix}
a & b \\
c & d
\end{matrix} $$

Aplicar la transpuesta

 $$ A^T = \begin{matrix}
a & c \\
b & d
\end{matrix} $$

y aplicamos el complejo conjugado

$$ A^\dagger = \overline{A^T} = \begin{matrix}
\overline{a} & \overline{c} \\
\overline{b} & \overline{d}
\end{matrix} $$

Ahora aplicamos

$$ (A^\dagger)^T = \begin{pmatrix} \overline{a} & \overline{b} \\ \overline{c} & \overline{d} \end{pmatrix} $$


Y finalmente aplicamos $ \overline{(A^\dagger)} $
$$ \overline{(A^\dagger)} = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix} $$
















**1.3)**

Demuestra el teorema de la diagonalización simultánea: Dos operadores hermíticos A y B conmutan si y solo si existe una base orto-normal respecto a la cual ambos A y B son diagonales.


Diagonilización simultanea implica que para dos matrices, comparten valores propios y vectores propios.

Teniendo $A^\dagger = A $ y $ B^\dagger = B $, si $A$ y $B$ conmutan y son del tipo $2x2$. Calculemos sus vectores y valores propios.

En caso de que ambos coincidan por ejempo $v_1 = [a, b]^T$ y $v_2 =  [c, d]^T$ y sus valores propio son $\lambda $ y $\mu $ donde $\lambda \neq \mu $

Diagonalizar ambas matrices es hallar $P$ y $D$


 $$ P_{AB} = \begin{matrix}
a & c \\
c & d
\end{matrix} $$

y

 $$ D_{AB} = \begin{matrix}
\lambda & 0 \\
0 & \mu
\end{matrix} $$




**1.4)**

Considere las matrices
 $$ A  = \begin{matrix}
0 & 1 & 0 \\
1 & 0 & 1\\
0 & 1 & 0
\end{matrix} $$

y


 $$ B  = \begin{matrix}
1 & 0 & 0 \\
0 & 0 & 0\\
0 & 0 & -1
\end{matrix} $$

a) Encuentre los autovalores y autovectores de A y B. Denote los autovectores de A como {|a1 ⟩ , |a2 ⟩ , |a3 ⟩} y los autovectores de B como {|b1 ⟩ , |b2 ⟩ , |b3 ⟩}. ¿Hay autovalores degenerados?




**1.5)**

In [1]:
import numpy as np
A = np.array([[0, 1, 0], [1, 0, 1], [0, 1,0]])
B = np.array([[1, 0, 0], [0, 0, 0], [0, 0,-1]])

In [3]:
autovalores_A, autovectores_A = np.linalg.eig(A)
autovalores_B, autovectores_B = np.linalg.eig(B)


array([-1.41,  0.  ,  1.41])

**a)**

Encuentre los autovalores y autovectores de A y B. Denote los autovectores de A como
{|a1 ⟩ , |a2 ⟩ , |a3 ⟩} y los autovectores de B como {|b1 ⟩ , |b2 ⟩ , |b3 ⟩}. ¿Hay autovalores degenerados?

In [7]:
print(list(np.round(autovalores_A, 2)))
print(list(np.round(autovalores_B, 2)))

[-1.41, 0.0, 1.41]
[1.0, 0.0, -1.0]


Los autovalores degenerados, también conocidos como autovalores múltiples o repetidos, son aquellos autovalores de una matriz que tienen multiplicidad algebraica mayor que uno. En otras palabras, un autovalor degenerado es aquel que aparece más de una vez en la lista de autovalores de una matriz. Para la mecánica cuántica,  *Un autovalor degenerado indica que hay múltiples estados cuánticos distintos que tienen la misma energía.*

En el caso de esta matriz $A$ y $B$ los vectores, no contiene ningun elemento repetido.

**b**

Muestre que cada uno de estos conjuntos forma una base completa, es decir, $⟨a_j|a_k⟩ = δ_{jk}$ y $ \sum_{i=1}^{3} |a_i⟩⟨a_i| = I_3$.


Para confirmar que estos dos conjuntos forma una base completa hay que revisar dos puntos, **la relación de completitud y la condición de ortonormalidad**

In [9]:
def completitud(autovectores):
  sum_array = np.zeros((3, 3))
  for i in autovectores:
    ket = i.T
    bra = i
    sum_array = np.outer(ket, bra)  + sum_array
  return np.round(sum_array, 3)

completitud_A = completitud(autovectores_A)
completitud_B = completitud(autovectores_B)

In [10]:
print(completitud_A)

[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [11]:
print(completitud_B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


La **relación de completitud** en el contexto de la mecánica cuántica ($   \sum_{i=1}^{3} |a_i⟩⟨a_i| = I_3  $) y la teoría de espacios de Hilbert. Esta relación establece que si tienes una serie de vectores de estado $ |a_i⟩ $
 ⟩ que forman una base ortonormal para un espacio de Hilbert de dimensión 3, entonces cualquier vector del espacio puede ser expresado como una combinación lineal de estos vectores de base.

El término  es un proyector o operador de proyección sobre el estado $  |a_i⟩⟨a_i| $. La suma de todos estos proyectores sobre una base ortonormal da como resultado el operador identidad $ I $ del espacio de Hilbert tridimensional. Esto también se conoce como la descomposición espectral del operador identidad.

En resumen, esta relación es una forma de expresar matemáticamente que un conjunto de vectores forma una base ortonormal completa para el espacio en el que viven.

La expresión $⟨a_j|a_k⟩ = δ_{jk}$ se llama condición de ortonormalidad. En el contexto de la mecánica cuántica o en el espacio de Hilbert, esto expresa que los estados $⟨a_j|a_k⟩ $ son ortogonales entre sí si $ i ≠ j $ y además, cada estado es normalizado (es decir, tiene longitud o norma 1).

La **ortogonalidad** se refiere a que el producto interno (o producto escalar) de dos vectores diferentes de la base es cero ($ i ≠ j $).
La normalización se refiere a que el producto interno de un vector consigo mismo es uno ($ i = j $).
Cuando ambos, ortogonalidad y normalización, se cumplen para una colección de vectores, decimos que estos vectores son ortonormales. En matrices, esta relación se traduce en que la matriz cuyas columnas son esos vectores es una matriz unitaria o matriz ortonormal. Esto significa que la matriz inversa es igual a su matriz adjunta (conjugada y transpuesta), lo que implica que multiplicar la matriz por su adjunta da la matriz identidad.

In [12]:
def condicion_ortonormalidad(autovectores):
  delta_kronecker = 0
  for i, bra in enumerate(autovectores):
    for j, ket in enumerate(autovectores):
      ket = ket.T
      if i != j:
        delta_kronecker = delta_kronecker + np.dot(bra, ket)
  return np.round(delta_kronecker, 3)
ortonormalidad_A = condicion_ortonormalidad(autovectores_A)
ortonormalidad_B = condicion_ortonormalidad(autovectores_B)
print(ortonormalidad_A, ortonormalidad_B )

-0.0 0.0
